#!/usr/bin/bash
#
# Credits: @MaximXRobot
# FROM TG-FileShare-Bot <https://t.me/+vBu5aXlocTkwNGM1>
# t.me/ShareFileXBot & t.me/MaximXRobot

# Attempt to Terminate and Remove previous session
if [ ! -d .git ]; then
    git clone https://github.com/AL3X-Github/TG-FileShare-Bot -b master tmp_git
    mv tmp_git/.git .
    rm -rf tmp_git
fi

# start
python3 main.py
